# Generated by Django 2.2 on 2023-05-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(default=12, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='selling_price',
            field=models.IntegerField(default=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
