# Generated by Django 2.2 on 2023-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20230507_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
