# Generated by Django 2.2 on 2023-05-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_item_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
