# Generated by Django 2.2 on 2023-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_auto_20230507_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
