# Generated by Django 2.2 on 2023-05-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_auto_20230507_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
