# Generated by Django 2.2 on 2023-05-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_auto_20230507_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default=321, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
