# Generated by Django 2.2 on 2023-05-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_auto_20230507_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='selling_price',
            field=models.FloatField(),
        ),
    ]
