# Generated by Django 2.2 on 2023-05-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_auto_20230508_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default=123, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
