# Generated by Django 2.2 on 2023-05-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shipping_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.FloatField(default=123456),
            preserve_default=False,
        ),
    ]
