# Generated by Django 2.2 on 2023-05-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_auto_20230509_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rebuy_till',
            field=models.IntegerField(default=0),
        ),
    ]
