# Generated by Django 2.2 on 2023-06-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_item_rebuy_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='TVA',
            field=models.FloatField(default=0),
        ),
    ]
