# Generated by Django 2.2 on 2023-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_item_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='TVA',
            field=models.FloatField(default=0),
        ),
    ]
