# Generated by Django 2.2 on 2023-08-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_auto_20230809_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
