# Generated by Django 2.2 on 2023-05-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_auto_20230509_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='created_at',
            new_name='time',
        ),
    ]
