# Generated by Django 2.2 on 2023-08-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_auto_20230509_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
