# Generated by Django 4.2.1 on 2024-01-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionExportNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
