# Generated by Django 2.2 on 2023-05-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.AutoField(default=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
