# Generated by Django 2.2 on 2023-08-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_auto_20230507_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
    ]
