# Generated by Django 4.2.1 on 2024-01-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0005_document_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
