# Generated by Django 4.2.9 on 2024-02-05 20:40

import Documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0007_alter_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=Documents.models.document_upload_to),
        ),
    ]
