# Generated by Django 4.2.9 on 2024-02-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0008_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/<django.db.models.fields.AutoField>/'),
        ),
    ]
