# Generated by Django 4.2.9 on 2024-02-05 21:30

import Documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0012_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.IntegerField(default=Documents.models.DocumentNumber.get_next_document_id, primary_key=True, serialize=False),
        ),
    ]
