# Generated by Django 4.2.9 on 2024-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0015_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/10/<function filename at 0x000001D5FFED44C0>'),
        ),
    ]
