# Generated by Django 4.2.9 on 2024-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0017_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
