# Generated by Django 4.2.9 on 2024-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0019_alter_document_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/<django.db.models.fields.AutoField>/'),
        ),
    ]
