# Generated by Django 4.2.9 on 2024-02-06 17:29

import Documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0022_alter_document_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.IntegerField(default=Documents.models.DocumentNumber.get_next_document_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
