# Generated by Django 4.2.9 on 2024-02-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0023_alter_document_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
